version: "3"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IBM_STOCK
      MYSQL_PASSWORD: 123456
