version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: STOCK_STREAMING
    ports:
      - "3306:3306"

  api:
    container_name: api
    build: ./
    links:
      - mysql
    ports:
      - "8000:8000"
